import { StyleSheet, Platform } from 'react-native';
import { ThemeColors, SHADOWS } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
  },
  greeting: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.primary,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: {
    color: colors.primaryForeground,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Space Grotesk',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  errorText: {
    fontSize: 14,
    color: colors.error,
    fontFamily: 'Inter',
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: colors.primary,
    borderRadius: 8,
  },
  retryButtonText: {
    color: colors.primaryForeground,
    fontWeight: '600',
    fontSize: 14,
    fontFamily: 'Space Grotesk',
  },
  listContent: {
    paddingBottom: 24,
  },
  jobCard: {
    marginHorizontal: 24,
    marginBottom: 12,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.1,
        shadowRadius: 10,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  jobCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  logoContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  logoPlaceholderText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  jobHeaderInfo: {
    flex: 1,
  },
  jobTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  companyName: {
    fontSize: 13,
    color: colors.primary,
    fontFamily: 'Inter',
    fontWeight: '500',
    marginTop: 2,
  },
  jobDescription: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    lineHeight: 20,
    marginBottom: 10,
  },
  jobMeta: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
  },
  jobMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  jobMetaText: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  jobFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  salaryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: isDark ? '#064e3b' : '#ECFDF5',
  },
  salaryText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#34d399' : '#059669',
    fontFamily: 'Inter',
  },
  timeAgo: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginLeft: 'auto',
  },
  applicantBadgeRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
    marginTop: 4,
  },
  applicantBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  applicantBadgeActive: {
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    borderWidth: 1,
    borderColor: isDark ? '#312e81' : '#C7D2FE',
  },
  applicantBadgeEmpty: {
    backgroundColor: colors.muted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  applicantBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Inter',
    color: colors.mutedForeground,
  },
  applicantBadgeTextActive: {
    color: colors.primary,
  },
  completionBanner: {
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    borderColor: isDark ? '#312e81' : '#C7D2FE',
    borderWidth: 1,
    borderRadius: 14,
    marginHorizontal: 24,
    marginBottom: 20,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.15,
        shadowRadius: 10,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  completionBannerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  completionBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  completionBannerText: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    lineHeight: 16,
    marginBottom: 10,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: colors.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  summaryContainer: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginHorizontal: 24,
    marginBottom: 20,
    padding: 16,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    padding: 12,
    alignItems: 'center',
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  summaryLabel: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
  resultsHeader: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 12,
  },
  resultsCount: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 6,
    textAlign: 'center',
    marginBottom: 20,
  },
  postJobButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.primary,
    borderRadius: 10,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.15,
        shadowRadius: 10,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  postJobButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
  },
});
