import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  backPlaceholder: {
    width: 40,
  },
  settingsButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  profileCard: {
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
    backgroundColor: colors.primary,
    marginBottom: 12,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 4,
  },
  userTitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginHorizontal: 24,
    marginBottom: 24,
  },
  statBox: {
    flex: 1,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  statLabel: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    fontWeight: '600',
    marginTop: 2,
  },
  menuSection: {
    marginHorizontal: 24,
    backgroundColor: colors.background,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    marginBottom: 32,
    marginTop: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuInfo: {
    flex: 1,
  },
  menuLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.error,
    gap: 8,
  },
  logoutIcon: {
    marginRight: 2,
  },
  logoutText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.error,
    fontFamily: 'Space Grotesk',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '75%',
    borderWidth: isDark ? 1 : 0,
    borderColor: colors.border,
    width: '100%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  closeBtn: {
    padding: 4,
  },
  modalScrollContent: {
    paddingBottom: 24,
  },
  modalSubTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginTop: 16,
    marginBottom: 8,
  },
  modalBodyText: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    lineHeight: 20,
    marginBottom: 12,
  },
  toggleContainerDark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginTop: 8,
    marginBottom: 8,
  },
  toggleTitleDark: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  toggleDescDark: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
});
