import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: colors.background,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    overflow: 'hidden',
  },
  headerAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 120,
  },
  heroCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  logoCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: isDark ? '#1e1b4b' : '#E0E7FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  logoLetter: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  titleContainer: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 4,
  },
  companyName: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  heroDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginBottom: 16,
  },
  heroFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  postedText: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginLeft: 6,
  },
  salaryText: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  applicantsBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.card,
    borderRadius: 100,
    padding: 8,
    paddingRight: 16,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  overlappingAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.card,
    marginLeft: -12,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applicantsText: {
    fontSize: 14,
    color: colors.mutedForeground,
    marginLeft: 12,
  },
  activeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#042f2e' : '#CCFBF1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 100,
    gap: 6,
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: isDark ? '#2D9488' : '#0D9488',
  },
  activeText: {
    color: isDark ? '#2D9488' : '#0D9488',
    fontSize: 12,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 16,
  },
  descriptionText: {
    fontSize: 15,
    color: colors.foreground,
    opacity: 0.85,
    lineHeight: 24,
    fontFamily: 'Inter',
    marginBottom: 24,
  },
  listContainer: {
    marginBottom: 24,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  listBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginTop: 8,
    marginRight: 12,
  },
  listText: {
    flex: 1,
    fontSize: 15,
    color: colors.foreground,
    lineHeight: 24,
    fontFamily: 'Inter',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 16,
  },
  applyButton: {
    flex: 1,
    height: 56,
    backgroundColor: colors.primary,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
  },
  bookmarkButtonOutline: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  // Recruiter specific
  recruiterCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    marginTop: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  recruiterInfo: {
    marginLeft: 12,
    flex: 1,
  },
  recruiterName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
  },
  recruiterRole: {
    fontSize: 14,
    color: colors.mutedForeground,
  },
  section: {
    marginBottom: 24,
  },
  avatarContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.mutedForeground,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  bottomSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  modalCenterContainer: {
    width: '100%',
    backgroundColor: colors.background,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    borderWidth: isDark ? 1 : 0,
    borderColor: colors.border,
  },
  alertIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: isDark ? '#3b0707' : '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 8,
    textAlign: 'center',
  },
  modalBodyText: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  modalButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  primaryModalButton: {
    backgroundColor: colors.primary,
  },
  secondaryModalButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.border,
  },
  primaryModalButtonText: {
    color: colors.primaryForeground,
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryModalButtonText: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '600',
  },
  bottomSheetContainer: {
    backgroundColor: colors.background,
    width: '100%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    marginTop: 'auto',
    borderWidth: isDark ? 1 : 0,
    borderColor: colors.border,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  bottomSheetTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  closeBtn: {
    padding: 6,
    backgroundColor: colors.muted,
    borderRadius: 20,
  },
  bottomSheetDesc: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginBottom: 24,
    lineHeight: 22,
  },
  actionRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.card,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  actionTextWrapper: {
    flex: 1,
  },
  actionTitleText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 4,
  },
  actionSubtitleText: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  cancelButton: {
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  coverLetterInput: {
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  resumeSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  resumeSelectRowActive: {
    borderColor: colors.primary,
    borderWidth: 1.5,
    backgroundColor: isDark ? '#1e293b' : '#f8fafc',
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.mutedForeground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonActive: {
    borderColor: colors.primary,
  },
  radioButtonInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  resumeSelectTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  resumeSelectTitleActive: {
    color: colors.primary,
  },
  resumeSelectSubtitle: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
});
