import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  topNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  stepChip: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stepText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    color: colors.mutedForeground,
  },
  skipButton: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  heroContainer: {
    flex: 1.8,
    paddingHorizontal: 24,
    paddingTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 240,
  },
  imageWrapper: {
    width: 220,
    height: 220,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  floatingChip: {
    position: 'absolute',
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderWidth: 0,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chipGoogle: {
    left: -32,
    top: 24,
  },
  chipMeta: {
    right: -24,
    top: 56,
  },
  chipApple: {
    left: -16,
    bottom: 32,
  },
  chipFilters: {
    left: -40,
    bottom: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  chipApplied: {
    right: -50,
    top: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
  },
  chipTracked: {
    right: -20,
    bottom: 10,
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  chipIconBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  appliedIconBox: {
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  bgPrimary: { backgroundColor: colors.primary },
  bgAccent: { backgroundColor: colors.accent },
  bgSurface: { backgroundColor: colors.surface },
  chipText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    color: colors.foreground,
  },
  filtersText: {
    fontFamily: 'Space Grotesk',
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    marginLeft: 4,
  },
  appliedTextTitle: {
    fontFamily: 'Space Grotesk',
    fontSize: 8,
    fontWeight: '700',
    color: colors.foreground,
  },
  appliedTextSubtitle: {
    fontFamily: 'Inter',
    fontSize: 8,
    color: colors.mutedForeground,
  },
  trackedTextNum: {
    fontFamily: 'Space Grotesk',
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryForeground,
  },
  trackedTextLabel: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: colors.primaryForeground,
    opacity: 0.9,
  },
  statsBadge: {
    position: 'absolute',
    right: -16,
    bottom: 40,
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
  },
  statsBadgeNumber: {
    fontFamily: 'Space Grotesk',
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryForeground,
    lineHeight: 20,
  },
  statsBadgeText: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: colors.primaryForeground,
    opacity: 0.8,
  },
  dotsContainer: {
    justifyContent: 'center',
  },
  textSection: {
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  badgeRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  platformBadge: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: isDark ? 'rgba(59,130,246,0.1)' : 'rgba(30,58,138,0.08)',
  },
  platformBadgeText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  title: {
    fontFamily: 'Space Grotesk',
    fontSize: 32,
    fontWeight: '700',
    color: colors.foreground,
    lineHeight: 36,
    marginBottom: 8,
  },
  titleHighlight: {
    color: colors.primary,
  },
  subtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: colors.mutedForeground,
    lineHeight: 20,
    marginBottom: 12,
  },
  statsRow: {
    flexDirection: 'row',
    marginBottom: 8,
    justifyContent: 'space-between',
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statNum: {
    fontFamily: 'Space Grotesk',
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  statLabel: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: colors.mutedForeground,
    marginTop: 2,
  },
  ctaSection: {
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryForeground,
    marginRight: 12,
  },
  arrowBox: {
    borderRadius: 8,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(255,255,255,0.2)',
  },
  trackingCardContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  glassCard: {
    width: 310,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  companyIconBg: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerText: {
    marginLeft: 12,
    flex: 1,
  },
  jobTitleText: {
    fontFamily: 'Space Grotesk',
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
  },
  companyNameText: {
    fontFamily: 'Inter',
    fontSize: 11,
    color: colors.mutedForeground,
    marginTop: 1,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 2,
  },
  timelineStep: {
    alignItems: 'center',
  },
  timelineNode: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  nodeActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  nodePulse: {
    backgroundColor: colors.background,
    borderColor: colors.primary,
  },
  nodePulseInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  nodeMuted: {
    backgroundColor: colors.background,
    borderColor: colors.border,
  },
  timelineText: {
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: '600',
    marginTop: 4,
  },
  textActive: {
    color: colors.primary,
  },
  textPulse: {
    color: colors.primary,
    fontWeight: '700',
  },
  textMuted: {
    color: colors.mutedForeground,
  },
  timelineLineActive: {
    flex: 1,
    height: 2,
    backgroundColor: colors.primary,
    marginBottom: 14,
  },
  timelineLineMuted: {
    flex: 1,
    height: 2,
    backgroundColor: colors.border,
    marginBottom: 14,
  },
  statusBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? 'rgba(59,130,246,0.1)' : 'rgba(30,58,138,0.04)',
    borderRadius: 8,
    padding: 8,
  },
  liveIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginRight: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    opacity: 0.4,
    transform: [{ scale: 1.5 }],
  },
  statusBadgeLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '600',
    color: colors.primary,
    flex: 1,
  },
  avatarGradient: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontFamily: 'Space Grotesk',
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryForeground,
  },
  matchScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  matchBadge: {
    backgroundColor: 'rgba(16,185,129,0.08)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
  },
  matchBadgeText: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '600',
    color: '#10B981',
  },
  tagBadge: {
    backgroundColor: isDark ? 'rgba(59,130,246,0.1)' : 'rgba(30,58,138,0.04)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tagBadgeText: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '600',
    color: colors.primary,
  },
  candidateActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  declineButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    borderColor: colors.border,
    borderWidth: 1,
  },
  declineButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 12,
    fontWeight: '700',
    color: colors.mutedForeground,
  },
  shortlistButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shortlistButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 12,
    fontWeight: '700',
    color: colors.primaryForeground,
  },
});
