import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  navHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginBottom: 12,
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  brandLogoBg: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: {
    fontFamily: 'Space Grotesk',
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
  },
  headingBlock: {
    marginBottom: 24
  },
  title: {
    fontFamily: 'Space Grotesk',
    fontSize: 30,
    fontWeight: '700',
    color: colors.foreground,
    lineHeight: 36,
    marginBottom: 8,
    textAlign: 'left',
  },
  subtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: colors.mutedForeground,
    textAlign: 'left',
    marginBottom: 24
  },

  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '600',
    color: colors.foreground,
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
  },
  inputFocus: {
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  inputError: {
    borderColor: colors.error,
  },
  textInput: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 14,
    color: colors.foreground,
    height: '100%',
    padding: 0,
  },
  inputIcon: {
    marginRight: 10,
  },
  eyeButton: {
    padding: 4,
  },
  errorText: {
    fontFamily: 'Inter',
    fontSize: 11,
    color: colors.error,
    marginTop: 6,
    marginLeft: 2,
  },
  submitButton: {
    backgroundColor: colors.secondary,
    borderRadius: 12,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  submitButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 16,
    fontWeight: '700',
    color: colors.secondaryForeground,
  },
  separatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  separatorText: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: colors.mutedForeground,
    marginHorizontal: 16,
    fontWeight: '600',
  },
  socialRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  socialButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: isDark ? colors.card : '#FFFFFF',
    height: 48,
    gap: 8,
  },
  socialButtonText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 4,
    width: '100%',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: colors.mutedForeground,
  },
  tabTextActive: {
    color: colors.primaryForeground,
  },
  toggleFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  toggleText: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: colors.mutedForeground,
  },
  toggleLink: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    marginLeft: 4,
  },
  globalErrorContainer: {
    marginBottom: 16,
    padding: 12,
    backgroundColor: isDark ? '#450a0a' : '#FEF2F2',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: isDark ? '#7f1d1d' : '#FCA5A5',
  },
  globalErrorText: {
    color: isDark ? '#f87171' : '#EF4444',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Inter-Medium',
  },
});
