import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
  },
  greeting: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.primary,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: {
    color: colors.primaryForeground,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Space Grotesk',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 24,
    gap: 12,
    marginBottom: 8,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 48,
    gap: 10,
  },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
    height: '100%',
    padding: 0,
  },
  chipListContainer: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.muted,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  chipTextActive: {
    color: colors.primaryForeground,
  },
  typeFilterContainer: {
    paddingHorizontal: 24,
    paddingBottom: 12,
    gap: 8,
  },
  typeFilter: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.transparent,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
  },
  typeFilterActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  typeFilterText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  typeFilterTextActive: {
    color: colors.secondaryForeground,
  },
  resultsHeader: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 12,
  },
  resultsCount: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  featuredSection: {
    marginVertical: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  seeAll: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
    fontFamily: 'Inter',
  },
  featuredRow: {
    paddingLeft: 24,
    paddingRight: 8,
    gap: 16,
  },
  featuredCard: {
    width: 280,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    marginRight: 16,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.1,
        shadowRadius: 10,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  featuredCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  featuredLogo: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  featuredLogoText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  featuredHeaderInfo: {
    flex: 1,
  },
  featuredTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  featuredCompany: {
    fontSize: 12,
    color: colors.primary,
    fontFamily: 'Inter',
    fontWeight: '500',
    marginTop: 1,
  },
  bookmarkIconContainer: {
    padding: 4,
  },
  featuredTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  featuredTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: colors.muted,
  },
  featuredTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  featuredSalaryTag: {
    backgroundColor: isDark ? '#064e3b' : '#ECFDF5',
  },
  featuredSalaryTagText: {
    color: isDark ? '#34d399' : '#059669',
  },
  featuredFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  featuredTimeAgo: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  listContent: {
    paddingBottom: 24,
  },
  jobCard: {
    marginHorizontal: 24,
    marginBottom: 10,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.1,
        shadowRadius: 10,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  jobCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  jobCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  jobLogo: {
    width: 46,
    height: 46,
    borderRadius: 13,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  jobLogoText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  jobHeaderInfo: {
    flex: 1,
    marginRight: 8,
  },
  jobTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  jobCompany: {
    fontSize: 12,
    color: colors.primary,
    fontFamily: 'Inter',
    fontWeight: '500',
    marginTop: 2,
  },
  viewButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.muted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  viewButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  applyButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.primary,
  },
  applyButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingMore: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 6,
    textAlign: 'center',
  },
  completionBanner: {
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    borderColor: isDark ? '#312e81' : '#C7D2FE',
    borderWidth: 1,
    borderRadius: 14,
    marginHorizontal: 24,
    marginBottom: 20,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.3 : 0.15,
        shadowRadius: 10,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  completionBannerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  completionBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Space Grotesk',
  },
  completionBannerText: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    lineHeight: 16,
    marginBottom: 10,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: colors.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '80%',
    borderWidth: isDark ? 1 : 0,
    borderColor: colors.border,
    width: '100%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  closeButton: {
    padding: 4,
  },
  modalSection: {
    marginBottom: 20,
  },
  modalSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 12,
  },
  modalChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modalChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.muted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  modalChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  modalChipTextActive: {
    color: colors.primaryForeground,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    marginBottom: 12,
  },
  resetButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  resetButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.mutedForeground,
    fontFamily: 'Space Grotesk',
  },
  filterApplyButton: {
    flex: 2,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterApplyButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
  },
});
