import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  backButtonPlaceholder: {
    width: 40,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  welcomeCard: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.4 : 0.15,
        shadowRadius: 12,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  welcomeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
    marginBottom: 4,
  },
  welcomeText: {
    fontSize: 13,
    color: colors.primaryForeground,
    opacity: 0.9,
    fontFamily: 'Inter',
    lineHeight: 18,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#3b0707' : '#FDE8E8',
    borderColor: isDark ? '#991b1b' : '#F98080',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 20,
  },
  errorBannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: isDark ? '#fca5a5' : '#9B1C1C',
    fontFamily: 'Inter',
  },
  formContainer: {
    gap: 20,
  },
  inputGroup: {
    width: '100%',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
    marginBottom: 8,
  },
  labelError: {
    color: colors.error,
  },
  input: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  inputError: {
    borderColor: colors.error,
    backgroundColor: isDark ? '#2a0808' : '#FDF2F2',
  },
  helperErrorText: {
    fontSize: 12,
    color: colors.error,
    fontFamily: 'Inter',
    marginTop: 4,
  },
  resumePickerCard: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.border,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.input,
    gap: 8,
  },
  resumePickerCardError: {
    borderColor: colors.error,
    backgroundColor: isDark ? '#2a0808' : '#FDF2F2',
  },
  resumePickerTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  resumePickerSubtitle: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  resumeAttachedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    backgroundColor: colors.background,
    justifyContent: 'space-between',
  },
  resumeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  resumeTextContainer: {
    flex: 1,
  },
  resumeName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  resumeSize: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
  removeResumeButton: {
    padding: 4,
  },
  footer: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.4 : 0.15,
        shadowRadius: 12,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  primaryButtonDisabled: {
    backgroundColor: colors.border,
    opacity: 0.7,
  },
  primaryButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 15,
    fontWeight: '700',
    color: colors.primaryForeground,
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  phonePrefixContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  phonePrefixText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  phoneTextInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
  },
});
