import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  backButtonPlaceholder: {
    width: 40,
  },
  saveDraftButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  saveDraftText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    fontFamily: 'Inter',
  },
  stepsContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.input,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 8,
  },
  stepHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepCurrentLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  stepCheckMark: {
    color: colors.primary,
  },
  stepCounter: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  segmentedBar: {
    flexDirection: 'row',
    gap: 4,
    height: 4,
    borderRadius: 2,
    overflow: 'hidden',
  },
  segment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
  },
  segmentDone: {
    backgroundColor: colors.primary,
    opacity: 0.5,
  },
  segmentActive: {
    backgroundColor: colors.primary,
    opacity: 1,
  },
  
  stepItem: { alignItems: 'center', gap: 4 },
  stepCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  stepCircleActive: { backgroundColor: colors.primary },
  stepNumber: { fontSize: 12, fontWeight: '700', color: colors.mutedForeground, fontFamily: 'Space Grotesk' },
  stepNumberActive: { color: colors.primaryForeground },
  stepLabel: { fontSize: 11, fontWeight: '600', color: colors.mutedForeground, fontFamily: 'Inter' },
  stepLabelActive: { color: colors.primary, fontWeight: '700' },
  stepDivider: { flex: 1, height: 2, backgroundColor: colors.border, marginHorizontal: 8, marginTop: -16 },
  stepDividerActive: { backgroundColor: colors.primary },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#3b0707' : '#FDE8E8',
    borderColor: isDark ? '#991b1b' : '#F98080',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 24,
  },
  errorBannerTextContainer: {
    flex: 1,
  },
  errorBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: isDark ? '#fca5a5' : '#9B1C1C',
    fontFamily: 'Space Grotesk',
  },
  errorBannerSubtitle: {
    fontSize: 12,
    color: isDark ? '#fca5a5' : '#9B1C1C',
    fontFamily: 'Inter',
    marginTop: 2,
  },
  formContainer: {
    gap: 20,
  },
  inputGroup: {
    width: '100%',
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  labelError: {
    color: colors.error,
  },
  input: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  inputError: {
    borderColor: colors.error,
    backgroundColor: isDark ? '#2a0808' : '#FDF2F2',
  },
  helperErrorText: {
    fontSize: 12,
    color: colors.error,
    fontFamily: 'Inter',
    marginTop: 4,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 12,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.muted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
  chipTextActive: {
    color: colors.primaryForeground,
  },
  reviewContainer: {
    gap: 16,
  },
  reviewHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 4,
  },
  reviewCard: {
    backgroundColor: colors.input,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 16,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 12,
  },
  reviewLabel: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    fontWeight: '600',
  },
  reviewVal: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  reviewDesc: {
    fontSize: 13,
    color: colors.foreground,
    fontFamily: 'Inter',
    lineHeight: 20,
  },
  footer: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  footerButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.4 : 0.15,
        shadowRadius: 12,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  primaryButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 15,
    fontWeight: '700',
    color: colors.primaryForeground,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderWidth: 1.5,
    borderRadius: 12,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontFamily: 'Space Grotesk',
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
  },
  skillInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  skillTextInput: {
    flex: 1,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.foreground,
    fontFamily: 'Inter',
  },
  addSkillButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addSkillButtonText: {
    color: colors.primaryForeground,
    fontFamily: 'Space Grotesk',
    fontWeight: '700',
    fontSize: 14,
  },
  skillsChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
    marginTop: 4,
  },
  skillChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    borderWidth: 1,
    borderColor: isDark ? '#312e81' : '#C7D2FE',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
  },
  skillChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: isDark ? '#818cf8' : colors.primary,
    fontFamily: 'Inter',
  },
  removeSkillBtn: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: isDark ? '#312e81' : '#C7D2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeSkillBtnText: {
    color: isDark ? '#818cf8' : colors.primary,
    fontSize: 11,
    fontWeight: '700',
    marginTop: -2,
  },
  skillHelpText: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 4,
  },
  reviewChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  reviewChip: {
    backgroundColor: isDark ? '#1e1b4b' : '#EEF2FF',
    borderWidth: 1,
    borderColor: isDark ? '#312e81' : '#C7D2FE',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  reviewChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: isDark ? '#818cf8' : colors.primary,
    fontFamily: 'Inter',
  },
  responsibilityList: {
    marginTop: 12,
    gap: 8,
  },
  responsibilityItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  responsibilityBullet: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.primary,
    marginTop: 6,
    flexShrink: 0,
  },
  responsibilityItemText: {
    flex: 1,
    fontSize: 13,
    color: colors.foreground,
    fontFamily: 'Inter',
    lineHeight: 19,
  },
  removeResponsibilityBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  emptyResponsibilities: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    marginTop: 12,
    backgroundColor: colors.input,
  },
  emptyResponsibilitiesText: {
    marginTop: 8,
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
  },
});
