import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  placeholder: {
    width: 44,
  },
  content: {
    padding: 24,
    paddingBottom: 120,
  },
  profileHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileInfoLeft: {
    flex: 1,
    paddingRight: 16,
  },
  avatarContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Space Grotesk',
  },
  candidateName: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Space Grotesk',
    color: colors.foreground,
    marginBottom: 4,
  },
  candidateEmail: {
    fontSize: 14,
    fontFamily: 'Inter',
    color: colors.mutedForeground,
    marginBottom: 8,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  section: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Space Grotesk',
    color: colors.foreground,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'Inter',
    color: colors.foreground,
    marginLeft: 8,
  },
  resumeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  resumeIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: isDark ? '#1e1b4b' : '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  resumeDetails: {
    flex: 1,
  },
  resumeTitle: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Space Grotesk',
    color: colors.foreground,
    marginBottom: 2,
  },
  resumeSubtitle: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '500',
  },
  coverLetterText: {
    fontSize: 14,
    fontFamily: 'Inter',
    color: colors.foreground,
    lineHeight: 22,
  },
  errorText: {
    fontSize: 16,
    fontFamily: 'Inter',
    color: colors.mutedForeground,
    textAlign: 'center',
    marginTop: 40,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 32 : 16,
  },
  footerButtonsContainer: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
  },
  rejectButton: {
    borderColor: colors.error,
    backgroundColor: isDark ? '#2a0808' : '#FEF2F2',
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  rejectText: {
    color: colors.error,
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    width: '100%',
  },
  acceptedBanner: {
    backgroundColor: isDark ? '#064e3b' : '#F0FDF4',
    borderColor: isDark ? '#34d399' : '#16A34A',
  },
  rejectedBanner: {
    backgroundColor: isDark ? '#2a0808' : '#FEF2F2',
    borderColor: isDark ? '#fda4af' : '#DC2626',
  },
  statusBannerText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter',
    color: colors.foreground,
  },
});
