import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  headerTitleText: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  settingsIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  mainInfoCard: {
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: isDark ? colors.card : '#F0F4FA', // Soft light-blue background tint in light mode
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  avatarContainer: {
    width: 96,
    height: 96,
    borderRadius: 24, // Rounded square
    overflow: 'hidden',
    backgroundColor: colors.primary,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: isDark ? colors.card : '#F0F4FA', // Matches card background
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 6,
  },
  userTitle: {
    fontSize: 14,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    fontWeight: '500',
    marginBottom: 8,
  },
  statusIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 24,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981', // Emerald green / Teal
  },
  statusText: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  statsCardContainer: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    paddingVertical: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  statCol: {
    flex: 1,
    alignItems: 'center',
  },
  statColDivider: {
    width: 1,
    height: 32,
    backgroundColor: colors.border,
  },
  statValText: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  statLblText: {
    fontSize: 12,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    fontWeight: '600',
    marginTop: 2,
  },
  section: {
    marginHorizontal: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? colors.surface : '#EEF2FF', // Very soft blue/indigo tint in light mode
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  infoTextContainer: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  resumeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? colors.card : '#EEF2FF', // Soft indigo background in light mode
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#C7D2FE',
    borderRadius: 20,
    padding: 16,
    gap: 12,
  },
  resumeIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resumeInfoContainer: {
    flex: 1,
  },
  resumeFileNameText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  resumeMetaText: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
  resumeSyncWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  settingsIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? colors.surface : '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  settingsLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  notificationBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.errorForeground,
    fontFamily: 'Space Grotesk',
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 40,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#FDA4AF', // Soft red border in light mode
    backgroundColor: colors.background,
    gap: 8,
  },
  logoutBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.error,
    fontFamily: 'Space Grotesk',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '75%',
    borderWidth: isDark ? 1 : 0,
    borderColor: colors.border,
    width: '100%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  closeBtn: {
    padding: 4,
  },
  modalScrollContent: {
    paddingBottom: 24,
  },
  modalSubTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
    marginTop: 16,
    marginBottom: 8,
  },
  modalBodyText: {
    fontSize: 13,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    lineHeight: 20,
    marginBottom: 12,
  },
  modalContentDark: {
    backgroundColor: colors.background,
    borderColor: colors.border,
  },
  modalTitleDark: {
    color: colors.foreground,
  },
  modalSubTitleDark: {
    color: colors.foreground,
  },
  modalBodyTextDark: {
    color: colors.mutedForeground,
  },
  toggleContainerDark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginTop: 8,
    marginBottom: 8,
  },
  toggleTitleDark: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.foreground,
    fontFamily: 'Space Grotesk',
  },
  toggleDescDark: {
    fontSize: 11,
    color: colors.mutedForeground,
    fontFamily: 'Inter',
    marginTop: 2,
  },
});
